# Generated by Django 4.2.5 on 2023-09-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('short_description', models.CharField(max_length=255)),
                ('modeling', models.CharField(max_length=255)),
                ('planimetry', models.CharField(max_length=255)),
                ('display', models.CharField(max_length=255)),
                ('software', models.CharField(max_length=255)),
                ('vegetation', models.CharField(max_length=255)),
                ('posproduction', models.CharField(max_length=255)),
                ('description', models.JSONField(default=list)),
            ],
        ),
    ]
