# Generated by Django 4.2.5 on 2023-09-13 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_projects_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='media',
            field=models.ImageField(null=True, upload_to='projects/images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='short_description',
            field=models.TextField(),
        ),
    ]
