# Generated by Django 4.2.5 on 2023-09-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_type_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='description',
            new_name='description_5',
        ),
        migrations.AddField(
            model_name='project',
            name='description_1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_3',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_4',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_6',
            field=models.JSONField(default=dict),
        ),
    ]
