# Generated by Django 4.2.5 on 2023-09-13 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_project_description_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description_5',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description_6',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
