# Generated by Django 4.2.5 on 2023-09-18 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_project_display_alter_project_modeling_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description_subtitle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
