# Generated by Django 4.2.5 on 2023-09-26 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_project_description_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='media',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
